version: '3'

services:
    mongodb:
        image: mongo:latest
        container_name: mongodb
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: test
            MONGO_INITDB_ROOT_PASSWORD: 321123
            MONGO_INITDB_DATABASE: mern-test
        ports:
            - 27017:27017
        volumes:
            - ./db/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    mern-api:
        build:
            dockerfile: Dockerfile.dev
            context: ./
        ports:
            - 4000:4000
            - 3000:3000
        environment:
            - DB_HOST=mongodb
        container_name: mern-api